"""Load and parse review-action results from a feedback directory.

Shared helpers used by ``review-action`` (read/write Action Taken) and
``review-feedback-browse`` (post-run results UI). No UI or agent dependencies.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from deep_architect.feedback_report import (
    NON_FINDING_FILES,
    get_severity,
    parse_markdown_finding,
)
from deep_architect.logger import get_logger

logger = get_logger(__name__)

_ACTION_TAKEN_HEADER = "## Action Taken"
_ACTION_TAKEN_FIELD_MAX_LEN = 500

# Display labels for harness status values.
OUTCOME_LABELS: dict[str, str] = {
    "completed": "Fixed",
    "rejected": "Rejected",
    "error": "Error",
    "skipped": "Skipped",
    "interrupted": "Interrupted",
    "dry-run": "Dry run",
}

# Preferred filter / sort order for action outcomes in the browser.
OUTCOME_ORDER: tuple[str, ...] = (
    "Fixed",
    "Error",
    "Skipped",
    "Rejected",
    "Interrupted",
    "Dry run",
    "Not processed",
)

SUMMARY_FILENAME = "review-action_summary.md"
_RUN_MARKER_RE = re.compile(
    r"<!--\s*review-action-run:\s*(.+?)\s*-->",
    re.MULTILINE,
)


@dataclass
class FindingStatus:
    """Persistent status for a finding — written to the .md file after each run."""

    status: str  # completed|error|skipped|rejected|dry-run|interrupted
    timestamp: str
    summary: str = ""
    commit_sha: str | None = None
    error_message: str | None = None


@dataclass(frozen=True)
class ActionFindingRow:
    """One finding row for the post-action browser / summary table."""

    finding_id: str
    path: Path
    source_file: str
    status: str | None  # None = not processed
    outcome_label: str
    summary: str
    commit_sha: str | None
    error_message: str | None
    timestamp: str
    severity: str = ""


@dataclass(frozen=True)
class ActionRunBlock:
    """Header stats from one ``review-action_summary.md`` run block."""

    started_at: str
    coding_agent: str
    restored: int
    processed: int
    committed: int
    skipped: int
    errors: int
    interrupted: bool
    progress: str
    total_findings: int | None
    cost_line: str | None


@dataclass(frozen=True)
class ActionReport:
    """Post-action view of a feedback directory."""

    directory: Path
    latest_run: ActionRunBlock | None
    prior_runs: list[ActionRunBlock]
    rows: list[ActionFindingRow]
    counts_by_outcome: dict[str, int]


def sanitize_action_taken_field(value: str) -> str:
    """Flatten a value for embedding as a single ``Key: value`` line.

    ``write_action_taken``'s block is parsed back by splitting on newlines and
    matching ``key: value`` per line (``read_action_taken``); an unflattened
    multi-line value would corrupt the parse.
    """
    flattened = value.replace("\r\n", "\\n").replace("\n", "\\n")
    if len(flattened) > _ACTION_TAKEN_FIELD_MAX_LEN:
        flattened = flattened[:_ACTION_TAKEN_FIELD_MAX_LEN] + "...(truncated, see logs)"
    return flattened


def has_action_taken(file_path: Path) -> bool:
    """Return True if a finding markdown has an ``## Action Taken`` section."""
    try:
        content = file_path.read_text(encoding="utf-8")
        return _ACTION_TAKEN_HEADER in content
    except OSError as exc:
        logger.error("Failed to read %s for action-taken check: %s", file_path, exc)
        return False


def read_action_taken(file_path: Path) -> FindingStatus | None:
    """Read the action-taken status from a finding markdown file."""
    try:
        content = file_path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.error("Failed to read %s: %s", file_path, exc)
        return None

    header_idx = content.find(_ACTION_TAKEN_HEADER)
    if header_idx == -1:
        return None

    block_start = content.find("\n", header_idx) + 1
    block_end = len(content)
    for marker in ("\n## ", "\n---\n", "\n*Generated by"):
        idx = content.find(marker, block_start)
        if 0 <= idx < block_end:
            block_end = idx

    block = content[block_start:block_end].strip()

    status_data: dict[str, str] = {}
    for line in block.splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            status_data[key.strip()] = value.strip()

    st = status_data.get("Status", "").strip()
    if not st:
        return None

    raw_ts = status_data.get("Timestamp", "")
    raw_summary = status_data.get("Summary", "")
    raw_commit = status_data.get("CommitSha", "")
    raw_error = status_data.get("ErrorMessage", "")

    return FindingStatus(
        status=st,
        timestamp=raw_ts.strip(),
        summary=raw_summary.strip(),
        commit_sha=raw_commit.strip() or None,
        error_message=raw_error.strip() or None,
    )


def write_action_taken(file_path: Path, status: FindingStatus) -> None:
    """Append or update the action-taken section in a finding markdown file."""
    separator = "\n" + _ACTION_TAKEN_HEADER + "\n"
    new_block = separator + "\n".join(
        [
            f"Status: {status.status}",
            f"Timestamp: {status.timestamp}",
            f"Summary: {sanitize_action_taken_field(status.summary)}",
        ]
    )
    if status.commit_sha:
        new_block += f"\nCommitSha: {status.commit_sha}"
    if status.error_message:
        new_block += (
            f"\nErrorMessage: {sanitize_action_taken_field(status.error_message)}"
        )
    new_block += "\n"

    try:
        content = file_path.read_text(encoding="utf-8")
    except OSError:
        content = ""

    header_idx = content.find(_ACTION_TAKEN_HEADER)
    if header_idx >= 0:
        content = content[:header_idx].rstrip("\n")

    content += new_block
    try:
        file_path.write_text(content, encoding="utf-8")
    except OSError as exc:
        logger.error("Failed to write action status to %s: %s", file_path, exc)


def outcome_label(status: FindingStatus) -> str:
    """Human-readable outcome label, including the verdict for rejections."""
    label = OUTCOME_LABELS.get(status.status, status.status)
    if status.status == "rejected" and status.summary.startswith("Verdict "):
        # "Verdict BACKLOG — not actioned" -> "Rejected (BACKLOG)"
        parts = status.summary.split()
        if len(parts) >= 2:
            return f"{label} ({parts[1]})"
    return label


def outcome_filter_key(label: str) -> str:
    """Normalize an outcome label to a filter bucket (e.g. Rejected (*))."""
    if label.startswith("Rejected"):
        return "Rejected"
    return label


def unescape_action_field(value: str) -> str:
    """Turn sanitized ``\\n`` sequences back into real newlines for display."""
    return value.replace("\\n", "\n")


def _parse_int_field(text: str, name: str) -> int:
    match = re.search(rf"^{re.escape(name)}:\s*(\d+)\s*$", text, re.MULTILINE)
    if match is None:
        return 0
    return int(match.group(1))


def parse_run_block(block: str, started_at: str) -> ActionRunBlock:
    """Parse one summary run block body into ``ActionRunBlock``."""
    agent_match = re.search(r"^Coding agent:\s*(.+)\s*$", block, re.MULTILINE)
    coding_agent = agent_match.group(1).strip() if agent_match else "unknown"

    interrupted_match = re.search(
        r"^Interrupted:\s*(yes|no)\s*$", block, re.MULTILINE | re.IGNORECASE
    )
    interrupted = bool(
        interrupted_match and interrupted_match.group(1).lower() == "yes"
    )

    progress_match = re.search(r"^Progress:\s*(.+)\s*$", block, re.MULTILINE)
    progress = progress_match.group(1).strip() if progress_match else ""

    total_findings: int | None = None
    total_match = re.search(
        r"Progress:\s*(\d+)\s+out of\s+(\d+)\s+findings",
        block,
        re.IGNORECASE,
    )
    if total_match:
        total_findings = int(total_match.group(2))

    cost_match = re.search(r"^Total cost:\s*(.+)\s*$", block, re.MULTILINE)
    cost_line = cost_match.group(0).strip() if cost_match else None

    # Prefer explicit "Run started:" if present; marker is the fallback.
    started_match = re.search(r"^Run started:\s*(.+)\s*$", block, re.MULTILINE)
    if started_match:
        started_at = started_match.group(1).strip()

    return ActionRunBlock(
        started_at=started_at,
        coding_agent=coding_agent,
        restored=_parse_int_field(block, "Restored"),
        processed=_parse_int_field(block, "Processed"),
        committed=_parse_int_field(block, "Committed"),
        skipped=_parse_int_field(block, "Skipped"),
        errors=_parse_int_field(block, "Errors"),
        interrupted=interrupted,
        progress=progress,
        total_findings=total_findings,
        cost_line=cost_line,
    )


def parse_summary_runs(summary_text: str) -> list[ActionRunBlock]:
    """Parse all run blocks from ``review-action_summary.md`` content (oldest first)."""
    matches = list(_RUN_MARKER_RE.finditer(summary_text))
    if not matches:
        return []

    runs: list[ActionRunBlock] = []
    for i, match in enumerate(matches):
        started_at = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(summary_text)
        body = summary_text[start:end]
        runs.append(parse_run_block(body, started_at))
    return runs


def _source_file_from_md(md_path: Path, content: str) -> str:
    bare_file_match = re.search(r"-?\s*\*\*File\*\*:?\s*(.+)", content)
    if bare_file_match:
        return bare_file_match.group(1).strip()
    parsed = parse_markdown_finding(md_path)
    if parsed is not None:
        return str(parsed.file_path)
    return "(unknown)"


def _row_from_finding_file(md_path: Path) -> ActionFindingRow:
    finding_id = md_path.stem
    try:
        content = md_path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.error("Failed to read finding %s: %s", md_path, exc)
        return ActionFindingRow(
            finding_id=finding_id,
            path=md_path,
            source_file="(unreadable)",
            status=None,
            outcome_label="Not processed",
            summary="",
            commit_sha=None,
            error_message=None,
            timestamp="",
        )

    source_file = _source_file_from_md(md_path, content)
    severity = get_severity(md_path)
    action = read_action_taken(md_path)
    if action is None:
        return ActionFindingRow(
            finding_id=finding_id,
            path=md_path,
            source_file=source_file,
            status=None,
            outcome_label="Not processed",
            summary="",
            commit_sha=None,
            error_message=None,
            timestamp="",
            severity=severity,
        )

    what = action.summary or ""
    if action.status == "error" and action.error_message:
        first_line = action.error_message.split("\\n", 1)[0]
        what = f"{what}: {first_line}" if what else first_line

    return ActionFindingRow(
        finding_id=finding_id,
        path=md_path,
        source_file=source_file,
        status=action.status,
        outcome_label=outcome_label(action),
        summary=what,
        commit_sha=action.commit_sha,
        error_message=action.error_message,
        timestamp=action.timestamp,
        severity=severity,
    )


def load_action_report(directory: Path) -> ActionReport:
    """Load post-action rows and latest run stats from a feedback directory.

    Raises:
        FileNotFoundError: if *directory* does not exist.
        NotADirectoryError: if *directory* is not a directory.
    """
    if not directory.exists():
        raise FileNotFoundError(f"Feedback directory does not exist: {directory}")
    if not directory.is_dir():
        raise NotADirectoryError(f"Not a directory: {directory}")

    rows: list[ActionFindingRow] = []
    for md_path in sorted(directory.glob("*.md")):
        if md_path.name in NON_FINDING_FILES:
            continue
        rows.append(_row_from_finding_file(md_path))

    prior_runs: list[ActionRunBlock] = []
    latest_run: ActionRunBlock | None = None
    summary_path = directory / SUMMARY_FILENAME
    if summary_path.is_file():
        try:
            summary_text = summary_path.read_text(encoding="utf-8")
            runs = parse_summary_runs(summary_text)
            if runs:
                latest_run = runs[-1]
                prior_runs = runs[:-1]
        except OSError as exc:
            logger.error("Failed to read summary %s: %s", summary_path, exc)

    counts = dict(Counter(outcome_filter_key(r.outcome_label) for r in rows))

    return ActionReport(
        directory=directory,
        latest_run=latest_run,
        prior_runs=prior_runs,
        rows=rows,
        counts_by_outcome=counts,
    )


def has_action_results(directory: Path) -> bool:
    """Return True if the directory has post-action data worth browsing."""
    if (directory / SUMMARY_FILENAME).is_file():
        return True
    try:
        for md_path in directory.glob("*.md"):
            if md_path.name in NON_FINDING_FILES:
                continue
            if has_action_taken(md_path):
                return True
    except OSError:
        return False
    return False


def rows_for_outcome_filter(
    report: ActionReport, filter_key: str | None
) -> list[ActionFindingRow]:
    """Return rows matching *filter_key* (``Fixed``, ``Error``, …) or all if None."""
    if filter_key is None or filter_key == "All":
        return list(report.rows)
    return [r for r in report.rows if outcome_filter_key(r.outcome_label) == filter_key]
