"""Unit tests for deep_architect.review_action_harness."""
from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from deep_architect.review_action_harness import (
    AgentConfig,
    OpencodeAgent,
    ReviewFinding,
    ValidationConfig,
    create_agent,
    is_valid_finding,
    parse_markdown_finding,
    process_findings,
)

# ---------------------------------------------------------------------------
# Sample markdown content matching review-analyzer output format
# ---------------------------------------------------------------------------

VALID_COMMENT_MARKDOWN = """# OCR Review Analysis

**Timestamp**: 2026-06-28T13:22:09Z

**Original OCR Finding**:

- **File**: src/example.py
- **Lines**: 10-15
- **Type**: Comment
- **Existing Code**:
```
def old_function():
    return "old"
```
- **Suggested Code**:
```
def new_function():
    return "new"
```
- **Review Comment**: This function should be updated for better performance

## LLM Analysis

**Verdict**: VALID

**Analysis**:
This change improves performance by using a more direct approach.

---

*Generated by review-analyzer.*
"""

REJECTED_MARKDOWN = VALID_COMMENT_MARKDOWN.replace(
    "**Verdict**: VALID", "**Verdict**: REJECTED"
)

BACKLOG_MARKDOWN = VALID_COMMENT_MARKDOWN.replace(
    "**Verdict**: VALID", "**Verdict**: BACKLOG"
)


# ---------------------------------------------------------------------------
# parse_markdown_finding
# ---------------------------------------------------------------------------


class TestParseMarkdownFinding:

    def test_parse_valid_comment_finding(self, tmp_path: Path) -> None:
        md_file = tmp_path / "abc12345-0.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        finding = parse_markdown_finding(md_file)

        assert finding is not None
        assert finding.file_path == Path("src/example.py")
        assert finding.line_start == 10
        assert finding.line_end == 15
        assert 'def old_function():\n    return "old"' in finding.existing_code
        assert 'def new_function():\n    return "new"' in finding.suggested_code
        assert "better performance" in finding.review_comment
        assert "performance" in finding.analysis
        assert finding.finding_id == "abc12345-0"

    def test_parse_warning_finding(self, tmp_path: Path) -> None:
        """Test parsing a warning-type finding (no lines, no existing/suggested)."""
        # Warnings don't have existing_code or suggested_code, so parsing
        # should fail (missing required sections)
        warning_md = """# OCR Review Analysis

**Timestamp**: 2026-06-28T13:22:09Z

**Original OCR Finding**:

- **File**: src/bar.py
- **Type**: Warning (timeout)
- **Message**: Context deadline exceeded

## LLM Analysis

**Verdict**: VALID

**Analysis**:
This warning indicates a timeout issue.

---

*Generated by review-analyzer.*
"""
        md_file = tmp_path / "warn001-0.md"
        md_file.write_text(warning_md)

        finding = parse_markdown_finding(md_file)
        # Warnings lack existing_code/suggested_code, so they can't be actioned
        assert finding is None

    def test_parse_missing_sections_returns_none(self, tmp_path: Path) -> None:
        incomplete = """# OCR Review Analysis

**Timestamp**: 2026-06-28T13:22:09Z

**Original OCR Finding**:

- **File**: test/example.py
- **Lines**: 10-15
"""
        md_file = tmp_path / "incomplete-0.md"
        md_file.write_text(incomplete)

        assert parse_markdown_finding(md_file) is None

    def test_parse_file_not_found(self) -> None:
        assert parse_markdown_finding(Path("/nonexistent/file.md")) is None

    def test_parse_finding_id_from_stem(self, tmp_path: Path) -> None:
        md_file = tmp_path / "my-custom-id.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        finding = parse_markdown_finding(md_file)
        assert finding is not None
        assert finding.finding_id == "my-custom-id"

    def test_parse_multiline_code_blocks(self, tmp_path: Path) -> None:
        """Test that code blocks with multiple lines are captured correctly."""
        multiline = """# OCR Review Analysis

**Original OCR Finding**:

- **File**: src/multi.py
- **Lines**: 1-5
- **Existing Code**:
```python
def func_a():
    x = 1
    y = 2
    return x + y
```
- **Suggested Code**:
```python
def func_a():
    return 3
```
- **Review Comment**: Simplify

## LLM Analysis

**Verdict**: VALID

**Analysis**:
Simplification is valid.

---

*Generated by review-analyzer.*
"""
        md_file = tmp_path / "multi-0.md"
        md_file.write_text(multiline)

        finding = parse_markdown_finding(md_file)
        assert finding is not None
        assert "x = 1" in finding.existing_code
        assert "y = 2" in finding.existing_code
        assert "return 3" in finding.suggested_code

    def test_parse_without_lines(self, tmp_path: Path) -> None:
        """Test parsing when lines section is absent."""
        no_lines = VALID_COMMENT_MARKDOWN.replace(
            "- **Lines**: 10-15\n", ""
        )
        md_file = tmp_path / "nolines-0.md"
        md_file.write_text(no_lines)

        finding = parse_markdown_finding(md_file)
        assert finding is not None
        assert finding.line_start is None
        assert finding.line_end is None


# ---------------------------------------------------------------------------
# is_valid_finding
# ---------------------------------------------------------------------------


class TestIsValidFinding:

    def test_valid_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "valid.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)
        assert is_valid_finding(md_file) is True

    def test_rejected_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "rejected.md"
        md_file.write_text(REJECTED_MARKDOWN)
        assert is_valid_finding(md_file) is False

    def test_backlog_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "backlog.md"
        md_file.write_text(BACKLOG_MARKDOWN)
        assert is_valid_finding(md_file) is False

    def test_no_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "no_verdict.md"
        md_file.write_text("# Some random content\nNo verdict here\n")
        assert is_valid_finding(md_file) is False

    def test_file_not_found(self) -> None:
        assert is_valid_finding(Path("/nonexistent/file.md")) is False


# ---------------------------------------------------------------------------
# OpencodeAgent
# ---------------------------------------------------------------------------


class TestOpencodeAgent:

    def test_default_init(self) -> None:
        agent = OpencodeAgent()
        assert agent.model == "standard/coder"
        assert "opencode" in agent.opencode_bin

    def test_custom_model(self) -> None:
        agent = OpencodeAgent(model="custom/model")
        assert agent.model == "custom/model"

    def test_custom_bin(self) -> None:
        agent = OpencodeAgent(opencode_bin="/custom/path")
        assert agent.opencode_bin == "/custom/path"

    @patch("deep_architect.review_action_harness.subprocess.run")
    async def test_apply_fix_success(self, mock_run: MagicMock) -> None:
        import json as _json

        ndjson = _json.dumps({"type": "result", "is_error": False, "result": "ok"})
        mock_run.return_value = MagicMock(
            returncode=0, stdout=ndjson, stderr=""
        )

        agent = OpencodeAgent()
        result = await agent.apply_fix(
            Path("test.py"), "old code", "new code", "context"
        )

        assert result is True
        mock_run.assert_called_once()

    @patch("deep_architect.review_action_harness.subprocess.run")
    async def test_apply_fix_failure(self, mock_run: MagicMock) -> None:
        mock_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="Error occurred"
        )

        agent = OpencodeAgent()
        result = await agent.apply_fix(
            Path("test.py"), "old code", "new code"
        )

        assert result is False

    @patch("deep_architect.review_action_harness.subprocess.run")
    async def test_apply_fix_timeout(self, mock_run: MagicMock) -> None:
        mock_run.side_effect = subprocess.TimeoutExpired(
            cmd="opencode", timeout=120
        )

        agent = OpencodeAgent()
        result = await agent.apply_fix(
            Path("test.py"), "old code", "new code"
        )

        assert result is False

    @patch("deep_architect.review_action_harness.subprocess.run")
    async def test_apply_fix_binary_not_found(
        self, mock_run: MagicMock
    ) -> None:
        mock_run.side_effect = FileNotFoundError()

        agent = OpencodeAgent(opencode_bin="/nonexistent/bin")
        result = await agent.apply_fix(
            Path("test.py"), "old code", "new code"
        )

        assert result is False


# ---------------------------------------------------------------------------
# create_agent
# ---------------------------------------------------------------------------


class TestCreateAgent:

    def test_create_opencode_agent(self) -> None:
        config = AgentConfig(provider="opencode", model="test/model")
        agent = create_agent(config)
        assert isinstance(agent, OpencodeAgent)
        assert agent.model == "test/model"

    def test_create_unsupported_agent_raises(self) -> None:
        config = AgentConfig(provider="unsupported", model="test/model")
        with pytest.raises(ValueError, match="Unsupported agent provider"):
            create_agent(config)

    def test_create_claude_agent_unavailable_raises(self) -> None:
        """When claude-agent-sdk is not importable (simulated), raising is expected."""
        config = AgentConfig(provider="claude", model="sonnet")
        # This will try to import claude_agent_sdk - since it's installed in
        # the project, we patch the import to simulate absence
        with patch.dict("sys.modules", {"claude_agent_sdk": None}):
            with pytest.raises(ImportError, match="claude-agent-sdk"):
                create_agent(config)


# ---------------------------------------------------------------------------
# ValidationConfig
# ---------------------------------------------------------------------------


class TestValidationConfig:

    def test_default_values(self) -> None:
        config = ValidationConfig(commands=[["ruff", "check"]])
        assert config.commands == [["ruff", "check"]]
        assert config.timeout == 30

    def test_custom_timeout(self) -> None:
        config = ValidationConfig(
            commands=[["ruff", "check"]], timeout=60
        )
        assert config.timeout == 60


# ---------------------------------------------------------------------------
# ReviewFinding dataclass
# ---------------------------------------------------------------------------


class TestReviewFinding:

    def test_creation(self) -> None:
        finding = ReviewFinding(
            file_path=Path("src/test.py"),
            line_start=1,
            line_end=10,
            existing_code="old",
            suggested_code="new",
            review_comment="fix this",
            analysis="it's broken",
            finding_id="test-0",
        )
        assert finding.file_path == Path("src/test.py")
        assert finding.line_start == 1
        assert finding.finding_id == "test-0"

    def test_optional_lines(self) -> None:
        finding = ReviewFinding(
            file_path=Path("src/test.py"),
            line_start=None,
            line_end=None,
            existing_code="old",
            suggested_code="new",
            review_comment="fix",
            analysis="",
            finding_id="test-1",
        )
        assert finding.line_start is None
        assert finding.line_end is None


# ---------------------------------------------------------------------------
# process_findings (integration-style)
# ---------------------------------------------------------------------------


class TestProcessFindings:

    def test_empty_directory(self, tmp_path: Path) -> None:
        """Test with an empty output directory."""
        output_dir = tmp_path / "empty"
        output_dir.mkdir()

        agent = OpencodeAgent()
        config = ValidationConfig(commands=[])
        stats = process_findings(
            output_dir, agent, config, max_retries=0, retry_delay=0.0
        )

        assert stats["processed"] == 0
        assert stats["errors"] == 0

    def test_nonexistent_directory(self) -> None:
        """Test with a non-existent output directory."""
        agent = OpencodeAgent()
        config = ValidationConfig(commands=[])
        stats = process_findings(
            Path("/nonexistent/dir"), agent, config, 0, 0.0
        )

        assert stats["processed"] == 0
        assert stats["errors"] == 0

    def test_skips_non_valid_findings(self, tmp_path: Path) -> None:
        """Test that non-VALID findings are skipped."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "rejected-0.md").write_text(REJECTED_MARKDOWN)
        (output_dir / "backlog-0.md").write_text(BACKLOG_MARKDOWN)

        agent = OpencodeAgent()
        config = ValidationConfig(commands=[])
        stats = process_findings(
            output_dir, agent, config, 0, 0.0
        )

        assert stats["processed"] == 2
        assert stats["skipped"] == 2
        assert stats["committed"] == 0

    def test_skips_summary_and_index(self, tmp_path: Path) -> None:
        """Test that SUMMARY.md and INDEX.md are skipped."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "SUMMARY.md").write_text("# Summary\n")
        (output_dir / "INDEX.md").write_text("# Index\n")

        agent = OpencodeAgent()
        config = ValidationConfig(commands=[])
        stats = process_findings(
            output_dir, agent, config, 0, 0.0
        )

        # SUMMARY.md and INDEX.md should not be counted
        assert stats["processed"] == 0

    def test_dry_run_commits_without_changes(self, tmp_path: Path) -> None:
        """Test dry-run mode counts as committed but makes no changes."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "valid-0.md").write_text(VALID_COMMENT_MARKDOWN)

        agent = OpencodeAgent()
        agent.apply_fix = AsyncMock(return_value=True)  # type: ignore[method-assign]
        config = ValidationConfig(commands=[])
        stats = process_findings(
            output_dir,
            agent,
            config,
            0,
            0.0,
            dry_run=True,
        )

        assert stats["processed"] == 1
        assert stats["committed"] == 1
        assert stats["errors"] == 0

    def test_validation_failure_skips_commit(self, tmp_path: Path) -> None:
        """Test that validation failure skips commit."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "valid-0.md").write_text(VALID_COMMENT_MARKDOWN)

        agent = OpencodeAgent()
        agent.apply_fix = AsyncMock(return_value=True)  # type: ignore[method-assign]

        # Use a command that will fail
        config = ValidationConfig(commands=[["false"]])

        with patch("deep_architect.review_action_harness.validate_git_repo"):
            stats = process_findings(
                output_dir, agent, config, 0, 0.0, dry_run=False
            )

        assert stats["processed"] == 1
        assert stats["skipped"] == 1
        assert stats["committed"] == 0

    def test_retry_logic(self, tmp_path: Path) -> None:
        """Test that retry logic works for transient failures."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "valid-0.md").write_text(VALID_COMMENT_MARKDOWN)

        # Agent fails first 2 attempts, succeeds on 3rd
        call_count = 0

        async def flaky_apply_fix(
            *args: object, **kwargs: object
        ) -> bool:
            nonlocal call_count
            call_count += 1
            return call_count >= 3

        agent = OpencodeAgent()
        agent.apply_fix = flaky_apply_fix  # type: ignore[method-assign]
        config = ValidationConfig(commands=[])

        with (
            patch(
                "deep_architect.review_action_harness.validate_git_repo"
            ),
            patch(
                "deep_architect.review_action_harness.git_commit",
                return_value=True,
            ),
        ):
            stats = process_findings(
                output_dir, agent, config, max_retries=3, retry_delay=0.001
            )

        assert call_count == 3
        assert stats["processed"] == 1
        assert stats["committed"] == 1

    def test_unparseable_valid_finding_is_skipped(
        self, tmp_path: Path
    ) -> None:
        """Test that VALID findings with no code blocks are skipped, not
        errors.  These are warning-type findings that can't be actioned."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        # Write a file that is VALID but has no code blocks (warning-type)
        broken_md = """# OCR Review Analysis

**Verdict**: VALID
"""
        (output_dir / "broken-0.md").write_text(broken_md)

        agent = OpencodeAgent()
        config = ValidationConfig(commands=[])
        stats = process_findings(
            output_dir, agent, config, 0, 0.0
        )

        assert stats["processed"] == 1
        assert stats["skipped"] == 1


# ---------------------------------------------------------------------------
# CodingAgent Protocol
# ---------------------------------------------------------------------------


class TestCodingAgentProtocol:

    def test_opencode_agent_implements_protocol(self) -> None:
        """Verify OpencodeAgent satisfies the CodingAgent protocol."""
        from deep_architect.review_action_harness import CodingAgent

        agent: CodingAgent = OpencodeAgent()
        assert hasattr(agent, "apply_fix")

    def test_claude_sdk_agent_implements_protocol(self) -> None:
        """Verify ClaudeSDKAgent satisfies the CodingAgent protocol."""
        from deep_architect.review_action_harness import (
            ClaudeSDKAgent,
            CodingAgent,
        )

        agent: CodingAgent = ClaudeSDKAgent()
        assert hasattr(agent, "apply_fix")
