"""Unit tests for deep_architect.review_action_harness."""
from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import git
import pytest

from deep_architect.coding_agents import OpencodeAgent
from deep_architect.config import HarnessConfig
from deep_architect.llm_judge import RuleEntry
from deep_architect.models.checks import (
    CheckProfile,
    QualityChecksConfig,
    StyleVerdict,
    StyleViolation,
)
from deep_architect.review_action_harness import (
    FindingStatus,
    ReviewFinding,
    _process_single_finding,
    has_action_taken,
    is_valid_finding,
    parse_args,
    parse_markdown_finding,
    process_findings,
    read_action_taken,
    write_action_taken,
)

# ---------------------------------------------------------------------------
# Shared test helpers
# ---------------------------------------------------------------------------


def _mock_repo(tmp_path: Path, commit_sha: str = "deadbeef00") -> MagicMock:
    """A MagicMock git.Repo whose working_dir resolves to a real path.

    Used by tests that don't care about the quality-check loop's behavior —
    combine with `get_modified_files` patched to `[]` so the loop trivially
    reports clean (no files, no profiles to run) and falls straight through
    to commit.
    """
    repo = MagicMock()
    repo.working_dir = str(tmp_path)
    repo.head.commit.hexsha = commit_sha
    return repo


def _init_repo(tmp_path: Path) -> git.Repo:
    """A real git repo for tests exercising the quality-check loop for real."""
    repo = git.Repo.init(tmp_path)
    (tmp_path / "README.md").write_text("# repo\n")
    repo.index.add(["README.md"])
    repo.index.commit("init")
    return repo


def _finding_markdown(
    file_path: str, existing: str, suggested: str, comment: str = "fix it"
) -> str:
    return (
        "# OCR Review Analysis\n\n"
        "**Original OCR Finding**:\n\n"
        f"- **File**: {file_path}\n"
        "- **Existing Code**:\n"
        f"```\n{existing}\n```\n"
        "- **Suggested Code**:\n"
        f"```\n{suggested}\n```\n"
        f"- **Review Comment**: {comment}\n\n"
        "## LLM Analysis\n\n"
        "**Verdict**: VALID\n\n"
        "**Analysis**:\nSome analysis.\n"
    )


# A synthetic "quality check" — fails while target.py contains the marker
# string "BAD", passes otherwise. Deterministic, no real linter dependency.
# Prints a message mentioning the file on failure so baseline-diff line
# matching (rule 2's modified-file-line refinement) has something to compare.
_BAD_MARKER_CHECK = (
    f'{sys.executable} -c "'
    "import pathlib, sys; "
    "c = pathlib.Path('target.py').read_text(); "
    "sys.exit(0) if 'BAD' not in c else (print('target.py: BAD marker found'), sys.exit(1))"
    '"'
)

# ---------------------------------------------------------------------------
# Sample markdown content matching review-analyzer output format
# ---------------------------------------------------------------------------

VALID_COMMENT_MARKDOWN = """# OCR Review Analysis

**Timestamp**: 2026-06-28T13:22:09Z

**Original OCR Finding**:

- **File**: src/example.py
- **Lines**: 10-15
- **Type**: Comment
- **Existing Code**:
```
def old_function():
    return "old"
```
- **Suggested Code**:
```
def new_function():
    return "new"
```
- **Review Comment**: This function should be updated for better performance

## LLM Analysis

**Verdict**: VALID

**Analysis**:
This change improves performance by using a more direct approach.

---

*Generated by review-analyzer.*
"""

REJECTED_MARKDOWN = VALID_COMMENT_MARKDOWN.replace(
    "**Verdict**: VALID", "**Verdict**: REJECTED"
)

BACKLOG_MARKDOWN = VALID_COMMENT_MARKDOWN.replace(
    "**Verdict**: VALID", "**Verdict**: BACKLOG"
)


# ---------------------------------------------------------------------------
# parse_markdown_finding
# ---------------------------------------------------------------------------


class TestParseMarkdownFinding:

    def test_parse_valid_comment_finding(self, tmp_path: Path) -> None:
        md_file = tmp_path / "abc12345-0.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        finding = parse_markdown_finding(md_file)

        assert finding is not None
        assert finding.file_path == Path("src/example.py")
        assert finding.line_start == 10
        assert finding.line_end == 15
        assert 'def old_function():\n    return "old"' in finding.existing_code
        assert 'def new_function():\n    return "new"' in finding.suggested_code
        assert "better performance" in finding.review_comment
        assert "performance" in finding.analysis
        assert finding.finding_id == "abc12345-0"

    def test_parse_warning_finding(self, tmp_path: Path) -> None:
        """Test parsing a warning-type finding (no lines, no existing/suggested)."""
        # Warnings don't have existing_code or suggested_code, so parsing
        # should fail (missing required sections)
        warning_md = """# OCR Review Analysis

**Timestamp**: 2026-06-28T13:22:09Z

**Original OCR Finding**:

- **File**: src/bar.py
- **Type**: Warning (timeout)
- **Message**: Context deadline exceeded

## LLM Analysis

**Verdict**: VALID

**Analysis**:
This warning indicates a timeout issue.

---

*Generated by review-analyzer.*
"""
        md_file = tmp_path / "warn001-0.md"
        md_file.write_text(warning_md)

        finding = parse_markdown_finding(md_file)
        # Warnings lack existing_code/suggested_code, so they can't be actioned
        assert finding is None

    def test_parse_missing_sections_returns_none(self, tmp_path: Path) -> None:
        incomplete = """# OCR Review Analysis

**Timestamp**: 2026-06-28T13:22:09Z

**Original OCR Finding**:

- **File**: test/example.py
- **Lines**: 10-15
"""
        md_file = tmp_path / "incomplete-0.md"
        md_file.write_text(incomplete)

        assert parse_markdown_finding(md_file) is None

    def test_parse_file_not_found(self) -> None:
        assert parse_markdown_finding(Path("/nonexistent/file.md")) is None

    def test_parse_finding_id_from_stem(self, tmp_path: Path) -> None:
        md_file = tmp_path / "my-custom-id.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        finding = parse_markdown_finding(md_file)
        assert finding is not None
        assert finding.finding_id == "my-custom-id"

    def test_parse_multiline_code_blocks(self, tmp_path: Path) -> None:
        """Test that code blocks with multiple lines are captured correctly."""
        multiline = """# OCR Review Analysis

**Original OCR Finding**:

- **File**: src/multi.py
- **Lines**: 1-5
- **Existing Code**:
```python
def func_a():
    x = 1
    y = 2
    return x + y
```
- **Suggested Code**:
```python
def func_a():
    return 3
```
- **Review Comment**: Simplify

## LLM Analysis

**Verdict**: VALID

**Analysis**:
Simplification is valid.

---

*Generated by review-analyzer.*
"""
        md_file = tmp_path / "multi-0.md"
        md_file.write_text(multiline)

        finding = parse_markdown_finding(md_file)
        assert finding is not None
        assert "x = 1" in finding.existing_code
        assert "y = 2" in finding.existing_code
        assert "return 3" in finding.suggested_code

    def test_parse_without_lines(self, tmp_path: Path) -> None:
        """Test parsing when lines section is absent."""
        no_lines = VALID_COMMENT_MARKDOWN.replace(
            "- **Lines**: 10-15\n", ""
        )
        md_file = tmp_path / "nolines-0.md"
        md_file.write_text(no_lines)

        finding = parse_markdown_finding(md_file)
        assert finding is not None
        assert finding.line_start is None
        assert finding.line_end is None


# ---------------------------------------------------------------------------
# is_valid_finding
# ---------------------------------------------------------------------------


class TestIsValidFinding:

    def test_valid_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "valid.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)
        assert is_valid_finding(md_file) is True

    def test_rejected_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "rejected.md"
        md_file.write_text(REJECTED_MARKDOWN)
        assert is_valid_finding(md_file) is False

    def test_backlog_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "backlog.md"
        md_file.write_text(BACKLOG_MARKDOWN)
        assert is_valid_finding(md_file) is False

    def test_no_verdict(self, tmp_path: Path) -> None:
        md_file = tmp_path / "no_verdict.md"
        md_file.write_text("# Some random content\nNo verdict here\n")
        assert is_valid_finding(md_file) is False

    def test_file_not_found(self) -> None:
        assert is_valid_finding(Path("/nonexistent/file.md")) is False


# ---------------------------------------------------------------------------
# ReviewFinding dataclass
# ---------------------------------------------------------------------------


class TestReviewFinding:

    def test_creation(self) -> None:
        finding = ReviewFinding(
            file_path=Path("src/test.py"),
            line_start=1,
            line_end=10,
            existing_code="old",
            suggested_code="new",
            review_comment="fix this",
            analysis="it's broken",
            finding_id="test-0",
        )
        assert finding.file_path == Path("src/test.py")
        assert finding.line_start == 1
        assert finding.finding_id == "test-0"

    def test_optional_lines(self) -> None:
        finding = ReviewFinding(
            file_path=Path("src/test.py"),
            line_start=None,
            line_end=None,
            existing_code="old",
            suggested_code="new",
            review_comment="fix",
            analysis="",
            finding_id="test-1",
        )
        assert finding.line_start is None
        assert finding.line_end is None


# ---------------------------------------------------------------------------
# process_findings (integration-style)
# ---------------------------------------------------------------------------


class TestProcessFindings:

    def test_empty_directory(self, tmp_path: Path) -> None:
        """Test with an empty output directory."""
        output_dir = tmp_path / "empty"
        output_dir.mkdir()

        agent = OpencodeAgent()
        stats = process_findings(
            output_dir, agent, 0, 0.0, HarnessConfig()
        )

        assert stats["processed"] == 0
        assert stats["errors"] == 0

    def test_nonexistent_directory(self) -> None:
        """Test with a non-existent output directory."""
        agent = OpencodeAgent()
        stats = process_findings(
            Path("/nonexistent/dir"), agent, 0, 0.0, HarnessConfig()
        )

        assert stats["processed"] == 0
        assert stats["errors"] == 0

    def test_skips_non_valid_findings(self, tmp_path: Path) -> None:
        """Test that non-VALID findings are skipped."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "rejected-0.md").write_text(REJECTED_MARKDOWN)
        (output_dir / "backlog-0.md").write_text(BACKLOG_MARKDOWN)

        agent = OpencodeAgent()
        stats = process_findings(
            output_dir, agent, 0, 0.0, HarnessConfig()
        )

        assert stats["processed"] == 2
        assert stats["skipped"] == 2
        assert stats["committed"] == 0

    def test_skips_summary_and_index(self, tmp_path: Path) -> None:
        """Test that SUMMARY.md and INDEX.md are skipped."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "SUMMARY.md").write_text("# Summary\n")
        (output_dir / "INDEX.md").write_text("# Index\n")

        agent = OpencodeAgent()
        stats = process_findings(
            output_dir, agent, 0, 0.0, HarnessConfig()
        )

        # SUMMARY.md and INDEX.md should not be counted
        assert stats["processed"] == 0

    def test_dry_run_commits_without_changes(self, tmp_path: Path) -> None:
        """Test dry-run mode counts as committed but makes no changes."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "valid-0.md").write_text(VALID_COMMENT_MARKDOWN)

        agent = OpencodeAgent()
        agent.apply_fix = AsyncMock(return_value=True)  # type: ignore[method-assign]
        stats = process_findings(
            output_dir,
            agent,
            0,
            0.0,
            HarnessConfig(),
            dry_run=True,
        )

        assert stats["processed"] == 1
        assert stats["committed"] == 1
        assert stats["errors"] == 0

    def test_retry_logic(self, tmp_path: Path) -> None:
        """Test that retry logic works for transient failures."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        (output_dir / "valid-0.md").write_text(VALID_COMMENT_MARKDOWN)

        # Agent fails first 2 attempts, succeeds on 3rd
        call_count = 0

        async def flaky_apply_fix(
            *args: object, **kwargs: object
        ) -> bool:
            nonlocal call_count
            call_count += 1
            return call_count >= 3

        agent = OpencodeAgent()
        agent.apply_fix = flaky_apply_fix  # type: ignore[method-assign]

        with (
            patch(
                "deep_architect.review_action_harness.validate_git_repo",
                return_value=_mock_repo(tmp_path),
            ),
            patch(
                "deep_architect.review_action_harness.get_modified_files",
                return_value=[],
            ),
            patch(
                "deep_architect.review_action_harness.git_commit",
                return_value=True,
            ),
        ):
            stats = process_findings(
                output_dir, agent, 3, 0.001, HarnessConfig()
            )

        assert call_count == 3
        assert stats["processed"] == 1
        assert stats["committed"] == 1

    def test_unparseable_valid_finding_is_skipped(
        self, tmp_path: Path
    ) -> None:
        """Test that VALID findings with no code blocks are skipped, not
        errors.  These are warning-type findings that can't be actioned."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        # Write a file that is VALID but has no code blocks (warning-type)
        broken_md = """# OCR Review Analysis

**Verdict**: VALID
"""
        (output_dir / "broken-0.md").write_text(broken_md)

        agent = OpencodeAgent()
        stats = process_findings(
            output_dir, agent, 0, 0.0, HarnessConfig()
        )

        assert stats["processed"] == 1
        assert stats["skipped"] == 1


# ---------------------------------------------------------------------------
# Quality-check loop (_process_single_finding)
# ---------------------------------------------------------------------------


class TestQualityCheckLoop:
    """Loop behavior matrix, exercised directly via _process_single_finding.

    Real git repos + a real (synthetic) check command so run_checks/
    capture_baseline/new_failures/git_restore_files all run for real; only
    load_quality_checks (discovery) and the LLM judge are patched.
    """

    def _setup(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[git.Repo, Path]:
        monkeypatch.chdir(tmp_path)
        repo = _init_repo(tmp_path)
        target = tmp_path / "target.py"
        target.write_text("GOOD\n")
        repo.index.add(["target.py"])
        repo.index.commit("add target")
        return repo, target

    def _checks_cfg(self) -> QualityChecksConfig:
        return QualityChecksConfig(
            profiles=[CheckProfile(name="p", paths=["**"], commands=[_BAD_MARKER_CHECK])]
        )

    def test_clean_first_iteration_commits_without_fix_check_failures(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "GOOD2"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("GOOD2\n")
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = AsyncMock(return_value=True)  # type: ignore[method-assign]

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=self._checks_cfg(),
            ),
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, HarnessConfig()
            )

        assert (status, committed, error) == ("committed", True, None)
        agent.fix_check_failures.assert_not_called()

    def test_programmatic_failure_then_fix_commits(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "BAD"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("BAD\n")  # introduces the failure
            return True

        fix_reports: list[str] = []

        async def fix_check_failures(
            files: list[Path], report: str, context: str = ""
        ) -> bool:
            fix_reports.append(report)
            target.write_text("FIXED\n")
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = fix_check_failures  # type: ignore[method-assign]

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=self._checks_cfg(),
            ),
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, HarnessConfig()
            )

        assert (status, committed, error) == ("committed", True, None)
        assert len(fix_reports) == 1
        assert "BAD marker found" in fix_reports[0]

    def test_style_only_failure_judge_invoked_then_retry_commits(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "GOOD2"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("GOOD2\n")  # programmatic check stays clean throughout
            return True

        fix_calls = 0

        async def fix_check_failures(
            files: list[Path], report: str, context: str = ""
        ) -> bool:
            nonlocal fix_calls
            fix_calls += 1
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = fix_check_failures  # type: ignore[method-assign]

        violation = StyleViolation(
            rule_id="PY-STY-001", severity="MUST", description="bad style", line=1
        )
        judge_calls = 0

        async def fake_judge_file(*args: object, **kwargs: object) -> StyleVerdict:
            nonlocal judge_calls
            judge_calls += 1
            return StyleVerdict(violations=[violation]) if judge_calls == 1 else StyleVerdict()

        empty_checks_cfg = QualityChecksConfig()  # no programmatic profiles

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=empty_checks_cfg,
            ),
            patch(
                "deep_architect.review_action_harness.load_llm_rules",
                return_value=[RuleEntry(path_glob="**/*.py", rule_text="some rule")],
            ),
            patch(
                "deep_architect.review_action_harness.judge_file",
                side_effect=fake_judge_file,
            ),
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, HarnessConfig()
            )

        assert (status, committed, error) == ("committed", True, None)
        assert fix_calls == 1
        assert judge_calls == 2

    def test_persistent_failure_reaches_cap_restores_and_errors(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "BAD"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("BAD\n")
            return True

        fix_calls = 0

        async def fix_check_failures(
            files: list[Path], report: str, context: str = ""
        ) -> bool:
            nonlocal fix_calls
            fix_calls += 1
            return True  # "fixes" it but never actually removes the marker

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = fix_check_failures  # type: ignore[method-assign]

        harness_config = HarnessConfig()
        harness_config.thresholds.check_max_fix_iterations = 2

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=self._checks_cfg(),
            ),
            patch(
                "deep_architect.review_action_harness.git_commit"
            ) as mock_commit,
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, harness_config
            )

        assert status == "error"
        assert committed is False
        assert error is not None and "2 iteration" in error
        assert fix_calls == 1  # cap=2 -> 1 fix attempt between the 2 check runs
        mock_commit.assert_not_called()
        # fail-closed: working tree restored to the pre-fix baseline
        assert target.read_text() == "GOOD\n"

    def test_pre_existing_failure_alone_does_not_block(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        repo = _init_repo(tmp_path)
        target = tmp_path / "target.py"
        target.write_text("BAD\n")  # already failing at baseline
        repo.index.add(["target.py"])
        repo.index.commit("add target with pre-existing failure")

        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "BAD", "BAD"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("BAD\n")  # unrelated no-op touch, still has the marker
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = AsyncMock(return_value=True)  # type: ignore[method-assign]

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=self._checks_cfg(),
            ),
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, HarnessConfig()
            )

        assert (status, committed, error) == ("committed", True, None)
        agent.fix_check_failures.assert_not_called()

    def test_skip_llm_checks_never_invokes_judge(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "GOOD2"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("GOOD2\n")
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = AsyncMock(return_value=True)  # type: ignore[method-assign]

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=QualityChecksConfig(),
            ),
            patch(
                "deep_architect.review_action_harness.load_llm_rules"
            ) as mock_load_rules,
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, HarnessConfig(), skip_llm_checks=True
            )

        assert (status, committed, error) == ("committed", True, None)
        mock_load_rules.assert_not_called()

    def test_check_max_fix_iterations_zero_report_only_never_blocks(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "BAD"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("BAD\n")  # would normally fail the check
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = AsyncMock(return_value=True)  # type: ignore[method-assign]

        harness_config = HarnessConfig()
        harness_config.thresholds.check_max_fix_iterations = 0

        with (
            patch("deep_architect.review_action_harness.validate_git_repo", return_value=repo),
            patch(
                "deep_architect.review_action_harness.load_quality_checks",
                return_value=self._checks_cfg(),
            ),
        ):
            status, committed, error = _process_single_finding(
                md_file, agent, 0, 0.0, False, harness_config
            )

        assert (status, committed, error) == ("committed", True, None)
        agent.fix_check_failures.assert_not_called()

    def test_sigint_during_check_loop_returns_interrupted(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import deep_architect.review_action_harness as rah

        repo, target = self._setup(tmp_path, monkeypatch)
        md_file = tmp_path / "finding-0.md"
        md_file.write_text(_finding_markdown("target.py", "GOOD", "GOOD2"))

        async def apply_fix(*args: object, **kwargs: object) -> bool:
            target.write_text("GOOD2\n")
            rah._shutdown_requested = True  # simulate CTRL-C right after the fix lands
            return True

        agent = OpencodeAgent()
        agent.apply_fix = apply_fix  # type: ignore[method-assign]
        agent.fix_check_failures = AsyncMock(return_value=True)  # type: ignore[method-assign]

        try:
            with (
                patch(
                    "deep_architect.review_action_harness.validate_git_repo", return_value=repo
                ),
                patch(
                    "deep_architect.review_action_harness.load_quality_checks",
                    return_value=self._checks_cfg(),
                ),
            ):
                status, committed, error = _process_single_finding(
                    md_file, agent, 0, 0.0, False, HarnessConfig()
                )
        finally:
            rah._shutdown_requested = False

        assert status == "interrupted"
        assert committed is False


# ---------------------------------------------------------------------------
# Finding Status Persistence
# ---------------------------------------------------------------------------


class TestFindingStatus:

    def test_creation(self) -> None:
        status = FindingStatus(
            status="completed",
            timestamp="2026-01-01T00:00:00+00:00",
            summary="Fix applied",
            commit_sha="abc12345",
        )
        assert status.status == "completed"
        assert status.commit_sha == "abc12345"
        assert status.error_message is None

    def test_error_status(self) -> None:
        status = FindingStatus(
            status="error",
            timestamp="2026-01-01T00:00:00+00:00",
            summary="Fix failed",
            error_message="Agent returned False",
        )
        assert status.status == "error"
        assert status.error_message == "Agent returned False"
        assert status.commit_sha is None


class TestWriteAndReadActionTaken:

    def test_write_creates_section(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Some content\n")

        status = FindingStatus(
            status="completed",
            timestamp="2026-01-01T00:00:00+00:00",
            summary="Fix applied",
            commit_sha="abc12345",
        )
        write_action_taken(md_file, status)

        content = md_file.read_text()
        assert "## Action Taken" in content
        assert "Status: completed" in content
        assert "CommitSha: abc12345" in content
        assert "Summary: Fix applied" in content

    def test_write_does_not_overwrite_existing(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Original content\n\n**Verdict**: VALID\n")

        status = FindingStatus(
            status="completed",
            timestamp="2026-01-01T00:00:00+00:00",
            summary="Fix applied",
            commit_sha="abc12345",
        )
        write_action_taken(md_file, status)

        content = md_file.read_text()
        assert "# Original content" in content
        assert "**Verdict**: VALID" in content
        assert "## Action Taken" in content

    def test_read_completed_status(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Original\n")

        status = FindingStatus(
            status="completed",
            timestamp="2026-01-01T00:00:00+00:00",
            summary="Fix applied",
            commit_sha="abc12345",
        )
        write_action_taken(md_file, status)

        read_status = read_action_taken(md_file)
        assert read_status is not None
        assert read_status.status == "completed"
        assert read_status.commit_sha == "abc12345"
        assert read_status.summary == "Fix applied"

    def test_read_error_status(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Original\n")

        status = FindingStatus(
            status="error",
            timestamp="2026-01-01T00:00:00+00:00",
            summary="Fix failed",
            error_message="Agent returned False",
        )
        write_action_taken(md_file, status)

        read_status = read_action_taken(md_file)
        assert read_status is not None
        assert read_status.status == "error"
        assert read_status.error_message == "Agent returned False"

    def test_read_no_section_returns_none(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Original content\nNo action section\n")

        assert read_action_taken(md_file) is None

    def test_has_action_taken_true(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Original\n\n## Action Taken\nStatus: completed\n")

        assert has_action_taken(md_file) is True

    def test_has_action_taken_false(self, tmp_path: Path) -> None:
        md_file = tmp_path / "test-0.md"
        md_file.write_text("# Original content\nNo action section\n")

        assert has_action_taken(md_file) is False

    def test_roundtrip_all_fields(self, tmp_path: Path) -> None:
        md_file = tmp_path / "roundtrip-0.md"
        md_file.write_text("# Finding\n\n**Verdict**: VALID\n")

        original = FindingStatus(
            status="completed",
            timestamp="2026-06-15T12:00:00+00:00",
            summary="Applied fix: removed unused import",
            commit_sha="deadbeef",
        )
        write_action_taken(md_file, original)

        restored = read_action_taken(md_file)
        assert restored is not None
        assert restored.status == original.status
        assert restored.timestamp == original.timestamp
        assert restored.summary == original.summary
        assert restored.commit_sha == original.commit_sha
        assert restored.error_message == original.error_message


class TestProcessFindingsPersistence:

    def test_completed_finding_skipped_on_restart(self, tmp_path: Path) -> None:
        """Test that a finding with completed status is skipped on restart."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        md_file = output_dir / "valid-0.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        # Simulate that the finding was completed in a prior run
        write_action_taken(
            md_file,
            FindingStatus(
                status="completed",
                timestamp="2026-01-01T00:00:00+00:00",
                summary="Fix applied",
                commit_sha="abc12345",
            ),
        )

        agent = OpencodeAgent()
        stats = process_findings(
            output_dir, agent, 0, 0.0, HarnessConfig()
        )

        assert stats["processed"] == 0
        assert stats["restored"] == 1
        assert stats["errors"] == 0

    def test_error_finding_retried_on_restart(self, tmp_path: Path) -> None:
        """Test that a finding with error status is retried on restart."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        md_file = output_dir / "valid-0.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        # Simulate that the finding errored in a prior run
        write_action_taken(
            md_file,
            FindingStatus(
                status="error",
                timestamp="2026-01-01T00:00:00+00:00",
                summary="Fix failed",
                error_message="Agent returned False",
            ),
        )

        agent = OpencodeAgent()
        agent.apply_fix = AsyncMock(return_value=True)  # type: ignore[method-assign]

        with (
            patch(
                "deep_architect.review_action_harness.validate_git_repo",
                return_value=_mock_repo(tmp_path),
            ),
            patch(
                "deep_architect.review_action_harness.get_modified_files",
                return_value=[],
            ),
            patch(
                "deep_architect.review_action_harness.git_commit",
                return_value=True,
            ),
        ):
            stats = process_findings(
                output_dir, agent, 0, 0.0, HarnessConfig()
            )

        assert stats["processed"] == 1
        assert stats["committed"] == 1

        # Verify the file was updated with completed status
        read_status = read_action_taken(md_file)
        assert read_status is not None
        assert read_status.status == "completed"

    def test_skip_errors_flag(self, tmp_path: Path) -> None:
        """Test that --skip-errors skips errored findings."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        md_file = output_dir / "valid-0.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        # Simulate that the finding errored in a prior run
        write_action_taken(
            md_file,
            FindingStatus(
                status="error",
                timestamp="2026-01-01T00:00:00+00:00",
                summary="Fix failed",
                error_message="Agent returned False",
            ),
        )

        agent = OpencodeAgent()
        agent.apply_fix = AsyncMock(return_value=True)  # type: ignore[method-assign]

        with (
            patch(
                "deep_architect.review_action_harness.validate_git_repo",
                return_value=_mock_repo(tmp_path),
            ),
            patch(
                "deep_architect.review_action_harness.get_modified_files",
                return_value=[],
            ),
            patch(
                "deep_architect.review_action_harness.git_commit",
                return_value=True,
            ),
        ):
            stats = process_findings(
                output_dir, agent, 0, 0.0, HarnessConfig(),
                skip_errors=True,
            )

        assert stats["processed"] == 0
        assert stats["skipped"] == 1

    def test_force_flag_reruns_completed(self, tmp_path: Path) -> None:
        """Test that --force re-runs completed findings."""
        output_dir = tmp_path / "feedback"
        output_dir.mkdir()

        md_file = output_dir / "valid-0.md"
        md_file.write_text(VALID_COMMENT_MARKDOWN)

        # Simulate that the finding was completed in a prior run
        write_action_taken(
            md_file,
            FindingStatus(
                status="completed",
                timestamp="2026-01-01T00:00:00+00:00",
                summary="Fix applied",
                commit_sha="abc12345",
            ),
        )

        agent = OpencodeAgent()
        agent.apply_fix = AsyncMock(return_value=True)  # type: ignore[method-assign]

        with (
            patch(
                "deep_architect.review_action_harness.validate_git_repo",
                return_value=_mock_repo(tmp_path),
            ),
            patch(
                "deep_architect.review_action_harness.get_modified_files",
                return_value=[],
            ),
            patch(
                "deep_architect.review_action_harness.git_commit",
                return_value=True,
            ),
        ):
            stats = process_findings(
                output_dir, agent, 0, 0.0, HarnessConfig(),
                force=True,
            )

        assert stats["processed"] == 1
        assert stats["committed"] == 1


# ---------------------------------------------------------------------------
# parse_args
# ---------------------------------------------------------------------------


class TestParseArgs:

    def test_provider_grok_accepted(self) -> None:
        args = parse_args(["feedback/", "--provider", "grok"])
        assert args.provider == "grok"

    def test_unknown_provider_rejected(self) -> None:
        with pytest.raises(SystemExit):
            parse_args(["feedback/", "--provider", "bogus"])


