"""Unit tests for deep_architect.feedback_report."""

from __future__ import annotations

from pathlib import Path

import pytest

from deep_architect.feedback_report import (
    NON_FINDING_FILES,
    ReviewFinding,
    analysis_preview,
    findings_for_verdict,
    get_verdict,
    is_valid_finding,
    line_range_label,
    load_feedback_dir,
    parse_markdown_finding,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _finding_md(
    *,
    file_path: str = "src/example.py",
    lines: str = "10-15",
    existing: str = "old_code()",
    suggested: str | None = "new_code()",
    comment: str = "fix it",
    verdict: str = "VALID",
    analysis: str = "Confirmed real issue.",
) -> str:
    suggested_block = ""
    if suggested is not None:
        suggested_block = f"- **Suggested Code**:\n```\n{suggested}\n```\n"
    return (
        "# OCR Review Analysis\n\n"
        "**Original OCR Finding**:\n\n"
        f"- **File**: {file_path}\n"
        f"- **Lines**: {lines}\n"
        f"- **Existing Code**:\n```\n{existing}\n```\n"
        f"{suggested_block}"
        f"- **Review Comment**: {comment}\n\n"
        "## LLM Analysis\n\n"
        f"**Verdict**: {verdict}\n\n"
        f"**Analysis**:\n{analysis}\n\n"
        "---\n\n"
        "*Generated by review-analyzer.*\n"
    )


def _write_finding(directory: Path, name: str, content: str) -> Path:
    path = directory / name
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# parse_markdown_finding / get_verdict
# ---------------------------------------------------------------------------


class TestParseMarkdownFinding:
    def test_full_finding(self, tmp_path: Path) -> None:
        md = _write_finding(tmp_path, "abc-0.md", _finding_md())
        finding = parse_markdown_finding(md)
        assert finding is not None
        assert finding.finding_id == "abc-0"
        assert finding.file_path == Path("src/example.py")
        assert finding.line_start == 10
        assert finding.line_end == 15
        assert finding.existing_code == "old_code()"
        assert finding.suggested_code == "new_code()"
        assert finding.review_comment == "fix it"
        assert "Confirmed" in finding.analysis

    def test_missing_suggested_code(self, tmp_path: Path) -> None:
        md = _write_finding(
            tmp_path, "no-sug-0.md", _finding_md(suggested=None)
        )
        finding = parse_markdown_finding(md)
        assert finding is not None
        assert finding.suggested_code == ""

    def test_missing_required_sections(self, tmp_path: Path) -> None:
        path = _write_finding(tmp_path, "bad.md", "# empty\n")
        assert parse_markdown_finding(path) is None

    def test_nonexistent_file(self) -> None:
        assert parse_markdown_finding(Path("/nonexistent/file.md")) is None


class TestGetVerdict:
    def test_valid(self, tmp_path: Path) -> None:
        md = _write_finding(tmp_path, "v.md", _finding_md(verdict="VALID"))
        assert get_verdict(md) == "VALID"

    def test_rejected(self, tmp_path: Path) -> None:
        md = _write_finding(tmp_path, "r.md", _finding_md(verdict="REJECTED"))
        assert get_verdict(md) == "REJECTED"

    def test_backlog(self, tmp_path: Path) -> None:
        md = _write_finding(tmp_path, "b.md", _finding_md(verdict="BACKLOG"))
        assert get_verdict(md) == "BACKLOG"

    def test_missing_verdict(self, tmp_path: Path) -> None:
        path = _write_finding(tmp_path, "n.md", "# no verdict\n")
        assert get_verdict(path) is None

    def test_nonexistent(self) -> None:
        assert get_verdict(Path("/nonexistent/file.md")) is None

    def test_is_valid_finding(self, tmp_path: Path) -> None:
        good = _write_finding(tmp_path, "g.md", _finding_md(verdict="VALID"))
        bad = _write_finding(tmp_path, "b.md", _finding_md(verdict="REJECTED"))
        assert is_valid_finding(good) is True
        assert is_valid_finding(bad) is False


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class TestHelpers:
    def test_analysis_preview_truncate(self) -> None:
        text = "word " * 50
        preview = analysis_preview(text, max_len=20)
        assert len(preview) == 20
        assert preview.endswith("…")

    def test_analysis_preview_short(self) -> None:
        assert analysis_preview("short") == "short"

    def test_line_range_label(self) -> None:
        assert line_range_label(10, 15) == ":10-15"
        assert line_range_label(7, 7) == ":7"
        assert line_range_label(3, None) == ":3"
        assert line_range_label(None, None) == ""


# ---------------------------------------------------------------------------
# load_feedback_dir
# ---------------------------------------------------------------------------


class TestLoadFeedbackDir:
    def test_missing_dir(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            load_feedback_dir(tmp_path / "nope")

    def test_not_a_directory(self, tmp_path: Path) -> None:
        f = tmp_path / "file.txt"
        f.write_text("x", encoding="utf-8")
        with pytest.raises(NotADirectoryError):
            load_feedback_dir(f)

    def test_empty_dir(self, tmp_path: Path) -> None:
        report = load_feedback_dir(tmp_path)
        assert report.findings == []
        assert report.counts == {}
        assert report.summary_text is None

    def test_skips_non_finding_files(self, tmp_path: Path) -> None:
        for name in NON_FINDING_FILES:
            (tmp_path / name).write_text(f"# {name}\n", encoding="utf-8")
        _write_finding(
            tmp_path,
            "keep-0.md",
            _finding_md(verdict="VALID", analysis="real finding"),
        )
        report = load_feedback_dir(tmp_path)
        assert len(report.findings) == 1
        assert report.findings[0].finding_id == "keep-0"
        assert report.summary_text is not None
        assert "SUMMARY.md" in report.summary_text or report.summary_text.startswith("#")

    def test_counts_and_grouping(self, tmp_path: Path) -> None:
        (tmp_path / "SUMMARY.md").write_text(
            "# Review Analysis Summary\n\nCoding agent: opencode (standard/coder)\n",
            encoding="utf-8",
        )
        _write_finding(
            tmp_path,
            "a-0.md",
            _finding_md(
                file_path="b/file.py",
                lines="20-22",
                verdict="VALID",
                analysis="valid A",
            ),
        )
        _write_finding(
            tmp_path,
            "b-1.md",
            _finding_md(
                file_path="a/file.py",
                lines="1-2",
                verdict="VALID",
                analysis="valid B",
            ),
        )
        _write_finding(
            tmp_path,
            "c-2.md",
            _finding_md(verdict="REJECTED", analysis="rejected"),
        )
        _write_finding(
            tmp_path,
            "d-3.md",
            _finding_md(verdict="BACKLOG", analysis="later"),
        )

        report = load_feedback_dir(tmp_path)
        assert len(report.findings) == 4
        assert report.counts == {"VALID": 2, "REJECTED": 1, "BACKLOG": 1}
        assert report.summary_text is not None
        assert "opencode" in report.summary_text

        # VALID first, then within VALID sort by source_file
        assert [f.verdict for f in report.findings] == [
            "VALID",
            "VALID",
            "REJECTED",
            "BACKLOG",
        ]
        valid = findings_for_verdict(report, "VALID")
        assert len(valid) == 2
        assert valid[0].source_file == "a/file.py"
        assert valid[1].source_file == "b/file.py"

    def test_degraded_partial_finding(self, tmp_path: Path) -> None:
        """Files that only have a verdict still appear (UNKNOWN path degraded)."""
        content = (
            "# OCR Review Analysis\n\n"
            "## LLM Analysis\n\n"
            "**Verdict**: BACKLOG\n\n"
            "**Analysis**:\n"
            "opencode execution timed out (>120s)\n"
        )
        _write_finding(tmp_path, "timeout-0.md", content)
        report = load_feedback_dir(tmp_path)
        assert len(report.findings) == 1
        f = report.findings[0]
        assert f.verdict == "BACKLOG"
        assert f.source_file == "(unknown)"
        assert "timed out" in f.raw_markdown

    def test_review_finding_dataclass(self) -> None:
        finding = ReviewFinding(
            file_path=Path("src/test.py"),
            line_start=1,
            line_end=10,
            existing_code="old",
            suggested_code="new",
            review_comment="fix this",
            analysis="it's broken",
            finding_id="test-0",
        )
        assert finding.finding_id == "test-0"


# ---------------------------------------------------------------------------
# CLI load failure path (no Textual)
# ---------------------------------------------------------------------------


class TestBrowseCli:
    def test_parse_args_default(self) -> None:
        from deep_architect.review_feedback_browse import parse_args

        args = parse_args([])
        assert args.feedback_dir == Path("feedback")
        assert args.mode == "auto"

    def test_parse_args_path(self) -> None:
        from deep_architect.review_feedback_browse import parse_args

        args = parse_args(["/tmp/feedback-proj"])
        assert args.feedback_dir == Path("/tmp/feedback-proj")

    def test_parse_args_mode(self) -> None:
        from deep_architect.review_feedback_browse import parse_args

        args = parse_args(["feedback/", "--mode", "action"])
        assert args.mode == "action"

    def test_main_missing_dir(self, tmp_path: Path) -> None:
        from deep_architect.review_feedback_browse import main

        rc = main([str(tmp_path / "missing")])
        assert rc == 1

    def test_main_empty_dir(self, tmp_path: Path) -> None:
        from deep_architect.review_feedback_browse import main

        rc = main([str(tmp_path)])
        assert rc == 1

    def test_resolve_browse_mode_auto(self, tmp_path: Path) -> None:
        from deep_architect.action_report import FindingStatus, write_action_taken
        from deep_architect.review_feedback_browse import resolve_browse_mode

        md = tmp_path / "a-0.md"
        md.write_text("# x\n", encoding="utf-8")
        assert resolve_browse_mode("auto", tmp_path) == "verdict"
        write_action_taken(
            md,
            FindingStatus(status="skipped", timestamp="t", summary="stale"),
        )
        assert resolve_browse_mode("auto", tmp_path) == "action"
        assert resolve_browse_mode("verdict", tmp_path) == "verdict"

    def test_format_action_helpers(self, tmp_path: Path) -> None:
        from deep_architect.action_report import (
            ActionFindingRow,
            ActionRunBlock,
        )
        from deep_architect.review_feedback_browse import (
            format_action_detail,
            format_action_row,
            format_action_stats,
        )

        run = ActionRunBlock(
            started_at="2026-08-08 19:53:57 UTC",
            coding_agent="opencode (opus)",
            restored=1,
            processed=28,
            committed=8,
            skipped=14,
            errors=6,
            interrupted=False,
            progress="28 out of 29 findings processed",
            total_findings=29,
            cost_line=None,
        )
        stats = format_action_stats(run, 29)
        assert "Committed" in stats
        assert "8" in stats

        row = ActionFindingRow(
            finding_id="abc-0",
            path=tmp_path / "abc-0.md",
            source_file="src/x.py",
            status="completed",
            outcome_label="Fixed",
            summary="Fix applied",
            commit_sha="deadbeef",
            error_message=None,
            timestamp="t",
        )
        (tmp_path / "abc-0.md").write_text(
            "# OCR\n- **File**: src/x.py\n"
            "- **Existing Code**:\n```\nold\n```\n"
            "- **Review Comment**: fix\n"
            "**Verdict**: VALID\n",
            encoding="utf-8",
        )
        line = format_action_row(row, 1)
        assert "Fixed" in line
        assert "deadbeef" in line
        detail = format_action_detail(row)
        assert "Action Taken" in detail
        assert "deadbeef" in detail
