"""Unit tests for deep_architect.action_report."""

from __future__ import annotations

from pathlib import Path

from deep_architect.action_report import (
    FindingStatus,
    has_action_results,
    has_action_taken,
    load_action_report,
    outcome_filter_key,
    outcome_label,
    parse_summary_runs,
    read_action_taken,
    rows_for_outcome_filter,
    unescape_action_field,
    write_action_taken,
)


def _finding_md(
    *,
    file_path: str = "src/example.py",
    verdict: str = "VALID",
) -> str:
    return (
        "# OCR Review Analysis\n\n"
        "**Original OCR Finding**:\n\n"
        f"- **File**: {file_path}\n"
        "- **Lines**: 10-12\n"
        "- **Existing Code**:\n```\nold()\n```\n"
        "- **Suggested Code**:\n```\nnew()\n```\n"
        "- **Review Comment**: fix it\n\n"
        "## LLM Analysis\n\n"
        f"**Verdict**: {verdict}\n\n"
        "**Analysis**:\nConfirmed.\n\n"
        "---\n\n"
        "*Generated by review-analyzer.*\n"
    )


def test_outcome_label_fixed() -> None:
    status = FindingStatus(status="completed", timestamp="t", summary="done")
    assert outcome_label(status) == "Fixed"


def test_outcome_label_rejected_with_verdict() -> None:
    status = FindingStatus(
        status="rejected",
        timestamp="t",
        summary="Verdict BACKLOG — not actioned",
    )
    assert outcome_label(status) == "Rejected (BACKLOG)"


def test_write_read_roundtrip(tmp_path: Path) -> None:
    md = tmp_path / "abc-0.md"
    md.write_text(_finding_md(), encoding="utf-8")
    write_action_taken(
        md,
        FindingStatus(
            status="completed",
            timestamp="2026-01-01T00:00:00",
            summary="Fix applied",
            commit_sha="deadbeef",
        ),
    )
    assert has_action_taken(md) is True
    restored = read_action_taken(md)
    assert restored is not None
    assert restored.status == "completed"
    assert restored.commit_sha == "deadbeef"
    assert restored.summary == "Fix applied"


def test_sanitize_multiline_error(tmp_path: Path) -> None:
    md = tmp_path / "err-0.md"
    md.write_text(_finding_md(), encoding="utf-8")
    write_action_taken(
        md,
        FindingStatus(
            status="error",
            timestamp="t",
            summary="Quality checks failed",
            error_message="## Style\n\n- bad line\nStatus: fake",
        ),
    )
    restored = read_action_taken(md)
    assert restored is not None
    assert restored.status == "error"
    assert "\\n" in (restored.error_message or "")
    assert unescape_action_field(restored.error_message or "").startswith("## Style")


def test_parse_summary_runs_latest() -> None:
    text = """<!-- review-action-run: 2026-08-08 18:00:00 UTC -->
# Review Action Summary

Run started:  2026-08-08 18:00:00 UTC
Coding agent: opencode (opus)

Restored:   0
Processed:  5
Committed:  0
Skipped:    1
Errors:     3
Interrupted: yes
Progress: 5 out of 29 findings processed

## Findings

| Finding | File | Outcome | Commit | What was done |
|---------|------|---------|--------|---------------|

<!-- review-action-run: 2026-08-08 19:53:57 UTC -->
# Review Action Summary

Run started:  2026-08-08 19:53:57 UTC
Coding agent: opencode (opus)

Restored:   1
Processed:  28
Committed:  8
Skipped:    14
Errors:     6
Total cost: $0.0000 across 0 agent call(s)
Interrupted: no
Progress: 28 out of 29 findings processed
"""
    runs = parse_summary_runs(text)
    assert len(runs) == 2
    assert runs[0].committed == 0
    assert runs[0].interrupted is True
    assert runs[1].committed == 8
    assert runs[1].skipped == 14
    assert runs[1].errors == 6
    assert runs[1].total_findings == 29
    assert runs[1].cost_line is not None
    assert "Total cost" in runs[1].cost_line


def test_load_action_report(tmp_path: Path) -> None:
    fixed = tmp_path / "aaa-0.md"
    fixed.write_text(_finding_md(file_path="src/a.py"), encoding="utf-8")
    write_action_taken(
        fixed,
        FindingStatus(
            status="completed",
            timestamp="t",
            summary="Fix applied",
            commit_sha="abc123",
        ),
    )
    err = tmp_path / "bbb-1.md"
    err.write_text(_finding_md(file_path="src/b.py"), encoding="utf-8")
    write_action_taken(
        err,
        FindingStatus(
            status="error",
            timestamp="t",
            summary="Quality checks failed",
            error_message="lint boom",
        ),
    )
    backlog = tmp_path / "ccc-2.md"
    backlog.write_text(_finding_md(file_path="src/c.py"), encoding="utf-8")
    write_action_taken(
        backlog,
        FindingStatus(
            status="rejected",
            timestamp="t",
            summary="Verdict BACKLOG — not actioned",
        ),
    )
    pending = tmp_path / "ddd-3.md"
    pending.write_text(_finding_md(file_path="src/d.py"), encoding="utf-8")

    (tmp_path / "review-action_summary.md").write_text(
        """<!-- review-action-run: 2026-08-08 19:53:57 UTC -->
# Review Action Summary

Run started:  2026-08-08 19:53:57 UTC
Coding agent: opencode (opus)

Restored:   0
Processed:  3
Committed:  1
Skipped:    0
Errors:     1
Interrupted: no
Progress: 3 out of 4 findings processed
""",
        encoding="utf-8",
    )

    report = load_action_report(tmp_path)
    assert len(report.rows) == 4
    assert report.latest_run is not None
    assert report.latest_run.committed == 1
    assert report.counts_by_outcome["Fixed"] == 1
    assert report.counts_by_outcome["Error"] == 1
    assert report.counts_by_outcome["Rejected"] == 1
    assert report.counts_by_outcome["Not processed"] == 1

    fixed_rows = rows_for_outcome_filter(report, "Fixed")
    assert len(fixed_rows) == 1
    assert fixed_rows[0].commit_sha == "abc123"
    assert fixed_rows[0].source_file == "src/a.py"

    err_rows = rows_for_outcome_filter(report, "Error")
    assert "lint boom" in err_rows[0].summary

    assert has_action_results(tmp_path) is True
    assert outcome_filter_key("Rejected (BACKLOG)") == "Rejected"


def test_has_action_results_false(tmp_path: Path) -> None:
    (tmp_path / "x-0.md").write_text(_finding_md(), encoding="utf-8")
    assert has_action_results(tmp_path) is False
