"""Unit tests for review-driver novelty metric and stop predicates."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from deep_architect.review_novelty import (
    OcrRunStats,
    StopReason,
    apply_ocr_stderr,
    consecutive_zero_novelty,
    count_findings_by_severity,
    count_high_signal_valid,
    count_valid_by_severity,
    count_verdicts,
    decide_stop,
    parse_ocr_run_stats,
    summarize_ocr_failure,
)


def _finding_md(
    *,
    file_path: str = "src/example.py",
    lines: str = "10-15",
    existing: str = "old_code()",
    suggested: str = "new_code()",
    comment: str = "fix it",
    verdict: str = "VALID",
    analysis: str = "Confirmed real issue.",
    severity: str | None = None,
) -> str:
    suggested_block = f"- **Suggested Code**:\n```\n{suggested}\n```\n"
    severity_line = f"- **Severity**: {severity}\n" if severity else ""
    return (
        "# OCR Review Analysis\n\n"
        "**Original OCR Finding**:\n\n"
        f"- **File**: {file_path}\n"
        f"- **Lines**: {lines}\n"
        f"{severity_line}"
        f"- **Existing Code**:\n```\n{existing}\n```\n"
        f"{suggested_block}"
        f"- **Review Comment**: {comment}\n\n"
        "## LLM Analysis\n\n"
        f"**Verdict**: {verdict}\n\n"
        f"**Analysis**:\n{analysis}\n\n"
        "---\n\n"
        "*Generated by review-analyzer.*\n"
    )


def _write_finding(directory: Path, name: str, content: str) -> Path:
    path = directory / name
    path.write_text(content, encoding="utf-8")
    return path


def _mixed_feedback_dir(tmp_path: Path) -> Path:
    """2 high VALID + 1 medium VALID + 1 low VALID + 1 high BACKLOG + 1 VALID no severity."""
    feedback = tmp_path / "feedback"
    feedback.mkdir()
    specs = (
        ("high-a.md", "VALID", "high"),
        ("high-b.md", "VALID", "high"),
        ("med-a.md", "VALID", "medium"),
        ("low-a.md", "VALID", "low"),
        ("backlog-high.md", "BACKLOG", "high"),
        ("valid-unknown.md", "VALID", None),
    )
    for name, verdict, severity in specs:
        _write_finding(
            feedback,
            name,
            _finding_md(file_path=f"src/{name}.py", verdict=verdict, severity=severity),
        )
    return feedback


class TestDecideStop:
    def test_ticket_sequence_converges_after_pass_4(self) -> None:
        history: list[int] = []
        reasons: list[StopReason] = []
        for value in (3, 1, 0, 0):
            history.append(value)
            reasons.append(decide_stop(novelty_history=history, k=2, max_passes=5))
        assert reasons == [
            StopReason.CONTINUE,
            StopReason.CONTINUE,
            StopReason.CONTINUE,
            StopReason.CONVERGED,
        ]
        assert history == [3, 1, 0, 0]

    def test_ticket_sequence_hits_max_passes(self) -> None:
        history: list[int] = []
        reasons: list[StopReason] = []
        for value in (1, 1, 1):
            history.append(value)
            reasons.append(decide_stop(novelty_history=history, k=2, max_passes=3))
        assert reasons[-1] == StopReason.MAX_PASSES
        assert StopReason.CONVERGED not in reasons

    def test_single_zero_continues(self) -> None:
        assert decide_stop(novelty_history=[0], k=2, max_passes=5) == StopReason.CONTINUE

    def test_two_zeros_converges(self) -> None:
        assert decide_stop(novelty_history=[0, 0], k=2, max_passes=5) == StopReason.CONVERGED

    def test_converged_beats_max_passes(self) -> None:
        assert (
            decide_stop(novelty_history=[1, 0, 0], k=2, max_passes=3) == StopReason.CONVERGED
        )

    def test_consecutive_zero_novelty_empty(self) -> None:
        assert consecutive_zero_novelty([]) == 0
        assert consecutive_zero_novelty([3, 1, 0, 0]) == 2
        assert consecutive_zero_novelty([0, 1, 0]) == 1


class TestCountHighSignalValid:
    def test_counts_only_high_and_medium_valid(self, tmp_path: Path) -> None:
        feedback = _mixed_feedback_dir(tmp_path)
        assert count_high_signal_valid(feedback) == 3

    def test_empty_dir_is_zero(self, tmp_path: Path) -> None:
        empty = tmp_path / "empty"
        empty.mkdir()
        assert count_high_signal_valid(empty) == 0

    def test_summary_only_dir_is_zero(self, tmp_path: Path) -> None:
        feedback = tmp_path / "summary-only"
        feedback.mkdir()
        (feedback / "SUMMARY.md").write_text("# Summary\n\nNo findings.\n", encoding="utf-8")
        assert count_high_signal_valid(feedback) == 0

    def test_missing_dir_raises(self, tmp_path: Path) -> None:
        missing = tmp_path / "does-not-exist"
        with pytest.raises(FileNotFoundError):
            count_high_signal_valid(missing)


class TestHistograms:
    def test_valid_by_severity(self, tmp_path: Path) -> None:
        feedback = _mixed_feedback_dir(tmp_path)
        assert count_valid_by_severity(feedback) == {
            "high": 2,
            "medium": 1,
            "low": 1,
            "unknown": 1,
        }

    def test_findings_by_severity_includes_backlog(self, tmp_path: Path) -> None:
        feedback = _mixed_feedback_dir(tmp_path)
        assert count_findings_by_severity(feedback) == {
            "high": 3,
            "medium": 1,
            "low": 1,
            "unknown": 1,
        }

    def test_verdicts(self, tmp_path: Path) -> None:
        feedback = _mixed_feedback_dir(tmp_path)
        counts = count_verdicts(feedback)
        assert counts["VALID"] == 5
        assert counts["BACKLOG"] == 1


class TestParseOcrRunStats:
    def test_plant_tracking_shaped_summary(self, tmp_path: Path) -> None:
        path = tmp_path / "code-review.json"
        path.write_text(
            json.dumps(
                {
                    "comments": [{"severity": "high"}],
                    "summary": {
                        "comments": 31,
                        "files_reviewed": 12,
                        "total_tokens": 412345,
                        "input_tokens": 300000,
                        "output_tokens": 112345,
                        "cache_read_tokens": 5000,
                        "elapsed": 241.0,
                    },
                }
            ),
            encoding="utf-8",
        )
        stats = parse_ocr_run_stats(path)
        assert stats.comments == 31
        assert stats.files_reviewed == 12
        assert stats.total_tokens == 412345
        assert stats.input_tokens == 300000
        assert stats.output_tokens == 112345
        assert stats.cache_read_tokens == 5000
        assert stats.elapsed == 241.0

    def test_comments_only_returns_empty_optionals(self, tmp_path: Path) -> None:
        path = tmp_path / "comments-only.json"
        path.write_text(
            json.dumps({"comments": [{"severity": "low", "content": "nit"}]}),
            encoding="utf-8",
        )
        stats = parse_ocr_run_stats(path)
        assert stats.comments is None
        assert stats.files_reviewed is None
        assert stats.total_tokens is None
        assert stats.input_tokens is None
        assert stats.output_tokens is None
        assert stats.cache_read_tokens is None
        assert stats.elapsed is None

    def test_missing_summary_is_not_an_error(self, tmp_path: Path) -> None:
        path = tmp_path / "no-summary.json"
        path.write_text(json.dumps({"status": "ok"}), encoding="utf-8")
        stats = parse_ocr_run_stats(path)
        assert stats.total_tokens is None
        assert stats.elapsed is None
        assert stats.status == "ok"

    def test_partial_status_and_retry_report(self, tmp_path: Path) -> None:
        path = tmp_path / "code-review-r1.json"
        path.write_text(
            json.dumps(
                {
                    "status": "partial",
                    "message": (
                        "Review partially complete: 1 finding(s); "
                        "13 of 16 selected item(s) failed."
                    ),
                    "llm": {"model": "nemotron-3-super"},
                    "summary": {
                        "comments": 1,
                        "files_reviewed": 16,
                        "total_tokens": 95216,
                        "elapsed": "20m1s",
                    },
                    "retry_report": {
                        "failed_requests": 23,
                        "requests": [
                            {
                                "outcome": "failed",
                                "attempts": [{"error_class": "timeout"}],
                            }
                            for _ in range(23)
                        ],
                    },
                }
            ),
            encoding="utf-8",
        )
        stats = parse_ocr_run_stats(path)
        assert stats.status == "partial"
        assert stats.files_reviewed == 16
        assert stats.files_failed == 13
        assert stats.failed_requests == 23
        assert stats.timeout_failures == 23
        assert stats.model == "nemotron-3-super"
        assert stats.comments == 1

    def test_failed_status_all_files(self, tmp_path: Path) -> None:
        path = tmp_path / "code-review-r2.json"
        path.write_text(
            json.dumps(
                {
                    "status": "failed",
                    "llm": {"model": "nemotron-3-super"},
                    "summary": {"files_reviewed": 16, "comments": 0},
                }
            ),
            encoding="utf-8",
        )
        stats = parse_ocr_run_stats(path)
        assert stats.status == "failed"
        assert stats.files_reviewed == 16
        assert stats.files_failed is None


class TestSummarizeOcrFailure:
    def test_all_timeouts_does_not_mention_api_key(self) -> None:
        stats = OcrRunStats(
            status="failed",
            message=(
                "review failed: all 16 file review(s) failed — "
                "check your LLM configuration and API key"
            ),
            failed_requests=25,
            timeout_failures=25,
            files_reviewed=16,
            files_failed=16,
        )
        text = summarize_ocr_failure(stats)
        assert "API key" not in text
        assert "context deadline exceeded" in text
        assert "25" in text
        assert "per-request HTTP deadline" in text
        assert "~5m" not in text

    def test_falls_back_to_stderr_error_line(self) -> None:
        text = summarize_ocr_failure(
            OcrRunStats(),
            "noise\nError: review failed: all 16 file review(s) failed — "
            "check your LLM configuration and API key\n",
            rc=1,
        )
        assert "all 16 file review(s) failed" in text
        assert "API key" not in text

    def test_deadline_in_stderr_without_retry_report(self) -> None:
        text = summarize_ocr_failure(
            OcrRunStats(status="failed"),
            "Error: LLM completion error: context deadline exceeded\n",
            rc=1,
        )
        assert text == "context deadline exceeded"

    def test_rc_fallback(self) -> None:
        assert summarize_ocr_failure(OcrRunStats(), rc=1) == "ocr exited rc=1"

    def test_apply_ocr_stderr_fills_files_failed(self) -> None:
        stats = apply_ocr_stderr(
            OcrRunStats(status="failed"),
            "Error: review failed: all 16 file review(s) failed — "
            "check your LLM configuration and API key\n",
        )
        assert stats.files_failed == 16
        assert stats.message is not None
        assert "all 16" in stats.message
